/* Autogenerated, edit autogen.pl or cmd.c instead! */
#define A1_READ_ONLY 0x0
#define A2_READ_ONLY 0x0
#define A1_READ_WRITE 0x1
#define A2_READ_WRITE 0x2

#define JIT_ARGS struct vcpu *curr_cpu, anyval *a1, anyval *a2
typedef void jitfunc (JIT_ARGS);

extern const unsigned int jit_protflags[];
extern jitfunc *jit_calls[];

#include "opcodes.h"
