#!/bin/sh

#
#  Argante virtual OS
#  ------------------
#
#  Background session support
#
#  Status: done
#
#  Author:     Michal Zalewski <lcamtuf@ids.pl>
#  Maintainer: Michal Zalewski <lcamtuf@ids.pl>
#

if [ -z "$LOGDIR" ]; then LOGDIR=/var/argante; fi
mkdir $LOGDIR &>/dev/null

if [ ! -w $LOGDIR ]; then
	mkdir $HOME/tmp &>/dev/null
	mkdir $HOME/tmp/argante &>/dev/null
	LOGDIR=$HOME/tmp/argante
fi;

echo "Argante OS - background session initialization"

if [ "$1" = "" ]; then
  echo "Usage: $0 path-to-argante [ script-to-execute ]"
  exit 1
fi

trap "" 1

echo >$LOGDIR/ses-$$.in

$1 $2 $3 $4 <$LOGDIR/ses-$$.in >$LOGDIR/ses-$$.log 2>&1 &

echo "<=> Please wait..."

sleep 2

if [ -d /proc/$! ]; then
  echo "<+> Argante session launched. Use 'agtses $!' to re-attach it."
else
  echo "<-> Argante session failed. Logfile:"
  tail $LOGDIR/ses-$$.log
fi
