/*
 * A2 Virtual Machine - Module dynamic loader
 * Copyright (c) 2001	James Kehl <ecks@optusnet.com.au>
 * 
 * This library is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Library General Public License as published
 * by the Free Software Foundation; version 2 of the License, with the
 * added restriction that it may only be converted to the version 2 of the
 * GNU General Public License.
 * 
 * This library is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 59 Temple Place, Suite 330, Boston, MA 02111-1307, USA.
 * ------------------------------------------------------------------------
 * 
 * VERY MUCH NOT AUTOGENERATED! DO NOT DELETE!
 *
 */
#include "autocfg.h"
#ifdef HAVE_UNISTD_H
#include <unistd.h>
#endif

#include <dlfcn.h>
#include "taskman.h"
#include "printk.h"
#include "modload.h"

/* Ummmm!
 * This crashes GDB! And potentially your kernel!
 */

static void *handles[A2_MAX_RSRVD];

void module_static_init() {
	int i;
	for(i=0;i<A2_MAX_RSRVD;i++) {
		handles[i]=NULL;
	}
}

static void do_null_error(char *type) {
	char *err;
	err=dlerror();
	if (err)
		printk2(PRINTK_ERR, "dynamic linker error: %s (%s)\n", err, type);
	else
		printk2(PRINTK_ERR, "module is bad: %s is NULL!\n", type);
}

/* RETURNS LID or -1 */
int module_dyn_load(char *file) {
	void *libhandle;
	moduleinitfunc *init;
	modulevcpufunc *start, *stop;
	unsigned lid;

	libhandle=dlopen(file, RTLD_NOW);
	if (!libhandle) {
		do_null_error("libhandle");
		return -1;
	}

	lid=lid_create();
	if (lid==-1) {
		dlclose(libhandle);
		return -1;
	}

	init=dlsym(libhandle, "module_init");
	if (!init) {
		do_null_error("module_init");
		dlclose(libhandle);
		return -1;
	}

	if (init(lid)) {
		moduleshutdownfunc *shutdown;
	
		shutdown=dlsym(libhandle, "module_shutdown");
		if (shutdown) 
			shutdown();
		else
			do_null_error("module_shutdown");
		dlclose(libhandle);
		return -1;
	}

	start=dlsym(libhandle, "module_vcpu_start");
	if (!start) do_null_error("module_vcpu_start");
	
	stop=dlsym(libhandle, "module_vcpu_stop");
	if (!stop) do_null_error("module_vcpu_start");
	
	lid_assign(lid, file, start, stop);
	
	if (lid >= A2_MAX_RSRVD)
		printk2(PRINTK_CRIT, "Loading module with excessive LID... unloading impossible!\n");
	else
		handles[lid]=libhandle;

	return lid;
}

/* RETURNS ZERO = success */
int module_dyn_unload(unsigned lid) {
	moduleshutdownfunc *shutdown;

	if (lid >= A2_MAX_RSRVD) {
		printk2(PRINTK_CRIT, "Unloading module with excessive LID\n");
		return 1;
	}

	if (!handles[lid]) {
		printk2(PRINTK_CRIT, "Unloading module we don't know about\n");
		return 1;
	}
	shutdown=dlsym(handles[lid], "module_shutdown");
	if (shutdown)
		shutdown();
	else
		do_null_error("module_shutdown");

	dlclose(handles[lid]);
	handles[lid]=NULL;
	lid_destroy(lid);
	return 0;
}

/* RETURNS ZERO=success */
int module_dyn_reload(unsigned lid) {
	printk2(PRINTK_ERR, "reload not yet implemented, sorry.\n");
	return 1;
}

