/*
 * A2 Virtual Machine - Module dynamic loader
 * Copyright (c) 2001	James Kehl <ecks@optusnet.com.au>
 * 
 * This library is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Library General Public License as published
 * by the Free Software Foundation; version 2 of the License, with the
 * added restriction that it may only be converted to the version 2 of the
 * GNU General Public License.
 * 
 * This library is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 59 Temple Place, Suite 330, Boston, MA 02111-1307, USA.
 * ------------------------------------------------------------------------
 * 
 * VERY MUCH NOT AUTOGENERATED! DO NOT DELETE!
 *
 */
#include "autocfg.h"
#include "compat/alloca.h"

#include <stdio.h>
#include <stdlib.h>
#ifdef HAVE_UNISTD_H
#include <unistd.h>
#endif
#include <string.h>

#ifndef NO_BROKEN_DLOPEN
#include <sys/stat.h>
#endif

#include <dlfcn.h>
#include "taskman.h"
#include "printk.h"
#include "modload.h"

/* Ummmm! This crashes GDB! And potentially your kernel!
 * Wtf? I don't remember why I wrote that. */

static void *handles[A2_MAX_RSRVD];

void module_static_init() {
	int i;
	for(i=0;i<A2_MAX_RSRVD;i++) {
		handles[i]=NULL;
	}
}

static void do_null_error(char *type) {
	char *err;
	err=dlerror();
	if (err)
		printk2(PRINTK_ERR, "dynamic linker error: %s (%s)\n", err, type);
	else
		printk2(PRINTK_ERR, "module is bad: %s is NULL!\n", type);
}

#ifndef NO_DLOPEN_FIX
#define RMHACKFILE if (oldname) unlink(file)
#else
#define RMHACKFILE
#endif

/* RETURNS LID or -1 */
int module_dyn_load(char *file) {
	void *libhandle;
	moduleinitfunc *init;
	modulevcpufunc *start, *stop;
	unsigned lid;
	int i;
#ifndef NO_DLOPEN_FIX
	char *tmp, *oldname=NULL;
	struct stat sbuf;
	ALLOCA_STACK;

	/* dlopen() on most systems is brokenish. It bases "load new" / 
	 * "use existing" on filenames, not file versions.
	 * This is an ugly hack */
	if (!stat(file, &sbuf)) {
		tmp=alloca(16 + 6);
		/* Should be enough to make collisions
		 * unlikely even with 64bit inodes(?) */
		sprintf(tmp, "./%.8x%.8x.so", (unsigned) sbuf.st_mtime, (unsigned) sbuf.st_ino);
		if (!link(file, tmp)) {
			oldname=file;
			file=tmp;
		}
	}
#endif
	libhandle=dlopen(file, RTLD_NOW);

	if (!libhandle) {
		do_null_error("libhandle");
		RMHACKFILE;
		return -1;
	}

	/* If you load the same file twice you only get one copy.
	 * This is bad: if we initialize it twice it will corrupt! */
	for(i=0;i<A2_MAX_RSRVD;i++) {
		if (handles[i]==libhandle) {
			printk2(PRINTK_CRIT, "that would load the _exact_ same module twice! (dlopen bug?)\n");
			dlclose(libhandle);
			RMHACKFILE;
			return -1;
		}
	}


	lid=lid_create();
	if (lid==-1) {
		dlclose(libhandle);
		RMHACKFILE;
		return -1;
	}

	init=dlsym(libhandle, "module_init");
	if (!init) {
		do_null_error("module_init");
		dlclose(libhandle);
		RMHACKFILE;
		return -1;
	}

	if (init(lid)) {
		moduleshutdownfunc *shutdown;
	
		shutdown=dlsym(libhandle, "module_shutdown");
		if (shutdown) 
			shutdown();
		else
			do_null_error("module_shutdown");
		dlclose(libhandle);
		RMHACKFILE;
		return -1;
	}

	start=dlsym(libhandle, "module_vcpu_start");
	if (!start) do_null_error("module_vcpu_start");
	
	stop=dlsym(libhandle, "module_vcpu_stop");
	if (!stop) do_null_error("module_vcpu_start");

#ifndef NO_DLOPEN_FIX
	if (oldname)
		lid_assign(lid, oldname, file, start, stop);
	else
		lid_assign(lid, file, NULL, start, stop);
#else
	lid_assign(lid, file, NULL, start, stop);
#endif
	
	if (lid >= A2_MAX_RSRVD)
		printk2(PRINTK_CRIT, "Loading module with excessive LID... unloading impossible!\n");
	else
		handles[lid]=libhandle;

	RMHACKFILE;
	return lid;
}

/* RETURNS ZERO = success */
int module_dyn_unload(unsigned lid) {
	moduleshutdownfunc *shutdown;

	if (lid >= A2_MAX_RSRVD) {
		printk2(PRINTK_CRIT, "Unloading module with excessive LID\n");
		return 1;
	}

	if (!handles[lid]) {
		printk2(PRINTK_CRIT, "Unloading module we don't know about\n");
		return 1;
	}
	shutdown=dlsym(handles[lid], "module_shutdown");
	if (shutdown)
		shutdown();
	else
		do_null_error("module_shutdown");

	dlclose(handles[lid]);
	handles[lid]=NULL;

	lid_destroy(lid);
	return 0;
}

/* RETURNS ZERO=success */
int module_dyn_reload(unsigned lid) {
	void *libhandle;
	moduleinitfunc *init;
	modulevcpufunc *start, *stop;
	char *file;
#ifndef NO_DLOPEN_FIX
	char *tmp, *oldname=NULL;
	struct stat sbuf;
	ALLOCA_STACK;
#endif
	if (lid >= A2_MAX_RSRVD) {
		printk2(PRINTK_CRIT, "Reloading module with excessive LID\n");
		return 1;
	}

	if (!handles[lid]) {
		printk2(PRINTK_CRIT, "Reloading module we don't know about\n");
		return 1;
	}

	file=NULL; //booga_XXX_func();

#ifndef NO_DLOPEN_FIX
	if (!stat(file, &sbuf)) {
		tmp=alloca(16 + 6);
		sprintf(tmp, "./%.8x%.8x.so", (unsigned) sbuf.st_mtime, (unsigned) sbuf.st_ino);
		if (!link(file, tmp)) {
			oldname=file;
			file=tmp;
		}
	}
#endif
	libhandle=dlopen(file, RTLD_NOW);

	if (!libhandle) {
		do_null_error("libhandle");
		RMHACKFILE;
		return -1;
	}

	if (handles[lid]==libhandle) {
		printk2(PRINTK_CRIT, "that would load the _exact_ same module twice! (dlopen bug?)\n");
		dlclose(libhandle);
		RMHACKFILE;
		return -1;
	}

	/* XXX: have to unregister and reregister syscalls! */

	start=dlsym(libhandle, "module_vcpu_start");
	if (!start) do_null_error("module_vcpu_start");
	
	stop=dlsym(libhandle, "module_vcpu_stop");
	if (!stop) do_null_error("module_vcpu_start");

#ifndef NO_DLOPEN_FIX
	if (oldname)
		lid_assign(lid, oldname, file, start, stop);
	else
		lid_assign(lid, file, NULL, start, stop);
#else
	lid_assign(lid, file, NULL, start, stop);
#endif
	
	dlclose(handles[lid]);
	handles[lid]=libhandle;
	RMHACKFILE;
	return lid;
}

