/* Autogenerated, please edit fs.c */
#include "modload.h"
#ifndef STATIC
int module_init
#else
int fs_init
#endif
(unsigned lid) {
	if (module_internal_init(lid)) return 1;
	register_syscall(200, fs_open); /* FS_OPEN */
	register_syscall(201, fs_open_existing); /* FS_OPEN_EXISTING */
	register_syscall(202, fs_open_create); /* FS_OPEN_CREATE */
	register_syscall(210, fs_close); /* FS_CLOSE */
	register_syscall(211, fs_read); /* FS_READ */
	register_syscall(212, fs_write); /* FS_WRITE */
	register_syscall(213, fs_flush); /* FS_FLUSH */
	register_syscall(214, fs_seek); /* FS_SEEK */
	register_syscall(215, fs_tell); /* FS_TELL */
	register_syscall(220, fs_wd_cwd); /* FS_WD_SET */
	register_syscall(221, fs_wd_pwd); /* FS_WD_GET */
	register_syscall(230, fs_open_dir); /* FS_OPEN_DIR */
	register_syscall(231, fs_read_dir); /* FS_READ_DIR */
	register_syscall(232, fs_make_dir); /* FS_MAKE_DIR */
	register_syscall(233, fs_stat); /* FS_STAT */
	register_syscall(240, fs_rename); /* FS_RENAME */
	register_syscall(241, fs_delete); /* FS_DELETE */
	return 0;
}

#ifndef STATIC
void module_vcpu_start
#else
void fs_vcpu_start
#endif
(struct vcpu *cpu) { module_internal_vcpu_start(cpu); }

#ifndef STATIC
void module_vcpu_stop
#else
void fs_vcpu_stop
#endif
(struct vcpu *cpu) { module_internal_vcpu_stop(cpu); }

#ifndef STATIC
void module_shutdown
#else
void fs_shutdown
#endif
() {
	module_internal_shutdown();	unregister_syscall(200); /* fs_open */
	unregister_syscall(201); /* fs_open_existing */
	unregister_syscall(202); /* fs_open_create */
	unregister_syscall(210); /* fs_close */
	unregister_syscall(211); /* fs_read */
	unregister_syscall(212); /* fs_write */
	unregister_syscall(213); /* fs_flush */
	unregister_syscall(214); /* fs_seek */
	unregister_syscall(215); /* fs_tell */
	unregister_syscall(220); /* fs_wd_cwd */
	unregister_syscall(221); /* fs_wd_pwd */
	unregister_syscall(230); /* fs_open_dir */
	unregister_syscall(231); /* fs_read_dir */
	unregister_syscall(232); /* fs_make_dir */
	unregister_syscall(233); /* fs_stat */
	unregister_syscall(240); /* fs_rename */
	unregister_syscall(241); /* fs_delete */
}

