/*
 * "lang2" - generator for lang2.h
 * Copyright (c) 2001	James Kehl <ecks@optusnet.com.au>
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 * -------------------------------------------------------------------------
 * The task of this is to translate language.h into a sane form.
 *
 * Sadly, the new types (and their compactness) don't sit well with
 * masks, and barely overlap the old language.h ones.
 * We approximate where we can. It's a mess.
 * -------------------------------------------------------------------------
 */

#include <stdio.h>
#include "bcode_op.h"
#include "language.h"

/* New mask def's:
 * The bits (1 << TYPE_UNSIGNED) indicates allowance of unsigned arg. etc.
 * TYPE_UNSIGNED	000 TYPE_SIGNED	001 TYPE_FLOAT	002 */

/* The bit (1 << TYPE_REGISTER) indicates the arg MUST be a register, ie.
 * IMM's disallowed. Without it, either is OK. Of course, IMMpointers are
 * still allowed...
 * TYPE_REGISTER	004 */

/* The bit (1 << TYPE_POINTER) indicates if a pointer is OK.
 * TYPE_POINTER		010 */

int main()
{
	int i;
	int t1, t2;

	puts("/* Autogenerated, edit language.h instead! */");
	puts(
	"struct op_desc2 {\n"
	"char *name;\n"
	"char bcode;\n"
	"int params;\n"
	"int tparam1;\n"
	"int tparam2;\n};\n");

	puts("#define OPS (sizeof(op)/sizeof(struct op_desc2))");
	puts("struct op_desc2 op[] = {");
	
	for(i=0;i<OPS;i++)
	{
		t1=t2=0;
	
		if (op[i].ureg1) t1|=(1 << TYPE_UNSIGNED);
		if (op[i].sreg1) t1|=(1 << TYPE_SIGNED);
		if (op[i].freg1) t1|=(1 << TYPE_FLOAT);
		if (!op[i].imm1) t1|=(1 << TYPE_REGISTER);
		if (op[i].immptr1 || op[i].uptr1) t1|=(1 << TYPE_POINTER);

		if (op[i].ureg2) t2|=(1 << TYPE_UNSIGNED);
		if (op[i].sreg2) t2|=(1 << TYPE_SIGNED);
		if (op[i].freg2) t2|=(1 << TYPE_FLOAT);
		if (!op[i].imm2) t2|=(1 << TYPE_REGISTER);
		if (op[i].immptr2 || op[i].uptr2) t2|=(1 << TYPE_POINTER);

		printf("{ \"%s\",\t%d,\t%d,\t0x%x,\t0x%x },\n", op[i].name, op[i].bcode, op[i].params, t1, t2);
	}
	puts("};");
	return 0;
}
