#!/bin/sh

# Sample network configuration script.

PATH=/sbin:/usr/sbin:$PATH

ifconfig eth0 10.1.0.1 netmask 255.255.0.0
ifconfig eth0:0 10.2.0.1 netmask 255.255.0.0
echo 0 >/proc/sys/net/ipv4/ip_forward

