#!/usr/bin/env bash

SYS=`uname -s`

echo "Configuring Argante for $SYS platform..."
rm -f conf.mk~ conf2.mk
mv conf.mk conf.mk~

echo
echo " **********************************************************************"
echo " * PLEASE READ Documentation/Portability REGARDING YOUR OPERATING     *"
echo " * SYSTEM IF YOU NOTICE ANY COMPILATION TIME OR RUNTIME PROBLEMS      *"
echo " **********************************************************************"
echo

echo -n "Remaking symbolic links..."
./make-links.sh
echo "done."

if [ "$SYS" = "Linux" ]; then
  echo "SYS=Linux" >> conf.mk
  echo "USE_PACKET=yes" >> conf.mk

  LIBC6="`ls -l /lib/libc*|grep -F -- -2.1`"
  LIBC6="$LIBC6`ls -l /lib/libc*|grep -F -- -2.2`"
  if [ "$LIBC6" = "" ]; then
    echo "WARNING: your libc subsystem is too old, reverting to old-style version."
  elif [ ! -z "$NOREADLINE" ]; then
    echo "NOTE: libreadline test disabled by user."
  elif [ -f /usr/include/readline/readline.h ]; then
    echo "USE_READLINE=yes" >> conf.mk

    if [ -f /usr/lib/libtinfo.so ]; then
        echo "USE_TINFO=yes" >> conf.mk
    fi
    echo "NOTE: libreadline detected, using it."
  else
    echo "NOTE: libreadline *NOT* detected, using old-style compilation."
  fi

  if [ -z "$NOSVGALIB" ]; then
  echo ">>> Performing svgalib compatibility test..."

  rm -f setup/svga-test
  gcc -fomit-frame-pointer -O9 -ffast-math -Wall -fforce-mem -fforce-addr \
      -fcaller-saves -fstrength-reduce -fthread-jumps -funroll-loops \
      -fcse-follow-jumps -fcse-skip-blocks -frerun-cse-after-loop \
      -fexpensive-optimizations -fschedule-insns2 -m486 -ldl -rdynamic -lm \
      -lvga setup/svga-test.c -o setup/svga-test >/dev/null 2>&1

  if [ ! -x setup/svga-test ]; then
    echo ">>> Test failed, compiling without gfx module."
  else
    echo ">>> Test successful, compiling with gfx module."
    echo "USE_SVGALIB=YES" >> conf.mk
  fi
  rm -f setup/svga-test
  else
    echo "NOTE: SVGALib test disabled by user."
  fi
fi

# Check if we should compile the GGI module
if [ -z "$NOGGILIB" ]; then 
	rm -f setup/ggi-test
	gcc -lggi setup/ggi-test.c -o setup/ggi-test >/dev/null 2>&1
	
	if [ ! -x setup/ggi-test ]; then
		echo "<+> GGI test failed, compiling without GGI module."
	else
		echo "<I> GGI test successful, compiling with GGI module."
		echo "USE_GGI=YES" >> conf.mk
	fi
	
	rm -f setup/ggi-test
else
	echo "<+> GGI test disabled by user."
fi

ISSOL=`echo $SYS|egrep -e 'Sun|Sola|Nis'`

if [ ! "$ISSOL" = "" ]; then
  echo "SYS=Solaris" >> conf.mk
  PATH="/usr/local/gnu/bin/:/usr/local/bin:$PATH"
fi

ISBSD=`echo $SYS|grep 'BSD'`

if [ ! "$ISBSD" = "" ]; then
  echo "SYS=BSD" >> conf.mk
  test "$SYS" = "OpenBSD" || echo "LDLIBS+=-Xlinker -export-dynamic" >> conf.mk
fi

ISIRX=`echo $SYS|grep 'IRIX'`

if [ ! "$ISIRX" = "" ]; then
  echo "SYS=IRIX" >> conf.mk
fi

ISAIX=`echo $SYS| grep 'AIX'`

if [ ! "$ISAIX" = "" ]; then
  echo "SYS=AIX" >> conf.mk
fi

if [ ! -e conf.mk ]; then
echo
echo "ERROR:"
echo "  Argante has not been tested with your system (`uname -s`)."
echo "  Please run (g)make anyway, cross your fingers, and report this."
exit 1
fi

# FIXME: SSL tests?

# GTK test
if [ -z "$NOGTK" ]; then
	echo ">>> Performing GTK compatibility test..."

	rm -f setup/gtk-test
	gcc `gtk-config --libs` `gtk-config --cflags` setup/gtk-test.c -o setup/gtk-test >/dev/null 2>&1

	if [ ! -x setup/gtk-test ]; then
		echo ">>> Test failed, compiling without GTK interface."
	else
		echo ">>> Test successful, compiling with GTK interface."
		echo "USE_GTK=YES" >> conf.mk
	fi
	
	rm -f setup/gtk-test 
else
	echo "NOTE: GTK test disabled by user."
fi

# ncurses test
if [ -z "$NOCURSES" ]; then
	echo ">>> Performing curses compatibility test..."

	rm -f setup/curses-test
	gcc -lcurses setup/curses-test.c -o setup/curses-test >/dev/null 2>&1

	if [ ! -x setup/curses-test ]; then
		echo ">>> Test failed, compiling without curses interface."
	else
		echo ">>> Test successful, compiling with curses interface."
		echo "USE_CURSES=YES" >> conf.mk
	fi

	rm -f setup/curses-test
else
	echo "NOTE: Curses test disabled by user."
fi

# Has the config changed, and needs a cleanup?
if [ -e conf.mk~ ]; then
  if cmp conf.mk~ conf.mk; then
    echo "Config files are identical!!!"
  else
    echo "Config files are different. Cleaning:"
    mv conf.mk conf2.mk
    mv conf.mk~ conf.mk
    gmake clean
    mv conf2.mk conf.mk
  fi
fi

echo "Argante is now configured for your system. (I hope.)"
echo "Just run GNU make now to build."

