.TH agtback 1 "23 November 2000"
.SH NAME
Argante background session initializer
.SH DESCRIPTION
Agtback is the background session initializer for 
.B Argante
- the virtual operarating system developed by
.B Argante Development Team
-
.RI < http://www.argante.org/ >

You can use it if you want to initialize any Argante session
and leave it running in background.

To use it, type

.B agtback path-to-argante [script name] [rootdir]

To work with this session, use
.B agtses.


Argante's homepage is
.RI < http://www.argante.org/ >
and that's the place you should look for more information on
this software. The other place is your 
.RI /usr/share/doc/argante/
directory - the 
.B README 
file explains (almost) everything...

.SH SEE ALSO
.BR argante (1),
.BR agtses (1),

.SH AUTHOR
Michal Zalewski <lcamtuf@ids.pl>,
manuals: honey@linuxnews.pl
