.TH agtc 1 "23 November 2000"
.SH NAME
Argante Bytecode Compiler
.SH DESCRIPTION
This utility is used to compile source code written in RSIS (Argante's
assembler).

The usage is very simple:
.B agtc filename.agt

It will produce a
.B filename.img
file that is a binary file for Argante.


This is a part of 
.B Argante
project - more information on it is avaiable at http://www.argante.org/

.SH SEE ALSO
.BR ahlt (1),
.BR acc (1),
.BR argante (1)

.SH AUTHOR
Michal Zalewski <lcamtuf@tpi.pl>,
manuals: honey@linuxnews.pl
