.TH agtses 1 "23 November 2000"
.SH NAME
Argante background session manager
.SH DESCRIPTION
Agtses is a background session manager for Argante - the virtual
operating system developed by
.B Argante Development Team.

To run it, just type
.B agtses session-pid 

That's all :-)


Argante's homepage is
.RI < http://www.argante.org/ >
and that's the place you should look for more information on
this software. The other place is your 
.RI /usr/share/doc/argante/
directory - the 
.B README 
file explains (almost) everything...

.SH SEE ALSO
.BR agtback (1),
.BR argante (1),

.SH AUTHOR
Michal Zalewski <lcamtuf@tpi.pl>,
manuals: honey@linuxnews.pl
