.TH ELIM 1 "22 November 2000" "elim" "elim"
.SH NAME
elim \- optimises Argante .agt files
.SH SYNOPSIS
.B elim
.SH "DESCRIPTION"
elim is a program performing heavy optimization on .agt files.
It ts is a shell script eliminating unused code.
.P
The program needs to be rewritten in C and optimized for higher speed.
Currently it needs bash to function properly.
It is a part of the 
.I Argante 
project.
.SH "SEE ALSO"
.BR acc(1),agtc(1)
.SH AUTHOR
Michal Zalewski <lcamtuf@ids.pl>
