/*
 * The task of this is to translate language.h into a sane form.
 */

#include <stdio.h>
#include "bcode.h"
#include "language.h"

int main()
{
	int i;

	puts("/* Autogenerated, edit language.h instead! */");
	puts(
	"struct op_desc2 {"
	"char *name;"
	"char bcode;"
	"int params;"
	"int tparam1;"
	"int tparam2; };\n");

	puts("#define OPS (sizeof(op)/sizeof(struct op_desc2))");
	puts("struct op_desc2 op[] = {");
	
	for(i=0;i<OPS;i++)
	{
		printf("{ \"%s\",\t%d,\t%d,\t0x%x,\t0x%x },\n", op[i].name, op[i].bcode, op[i].params,
			(op[i].imm1 << TYPE_IMMEDIATE) | (op[i].ureg1 << TYPE_UREG) | (op[i].sreg1 << TYPE_SREG) | (op[i].freg1 << TYPE_FREG) | (op[i].immptr1 << TYPE_IMMPTR) | (op[i].uptr1 << TYPE_UPTR),
			(op[i].imm2 << TYPE_IMMEDIATE) | (op[i].ureg2 << TYPE_UREG) | (op[i].sreg2 << TYPE_SREG) | (op[i].freg2 << TYPE_FREG) | (op[i].immptr2 << TYPE_IMMPTR) | (op[i].uptr2 << TYPE_UPTR));
	}
	puts("};");
	return 0;
}
